# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ecvExportGeoTiffall.py
# Created on: 2014-03-31 10:38:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Converts netCDF files to raster and then copys the raster for
# export as Geotiff
# Requirement: ArcGIS installed
# Author: Kimberly Peng
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

#assigns initial year
year=1978
while (year < 2011):
    #converts year to string
    strYear=str(year)

    #specifies output directory - USER TO MODIFY
    #outputDir="C:\\Users\\kpeng\\Desktop\\ecvGeotiffs\\"
    outputDir="G:\\ECV_SOIL_MOISTURE_TIFS\\"  + strYear + "\\"

    #specifies input directory - USER TO MODIFY
    #inputDir= '/Users/kpeng/Desktop/ecv' + "/" + strYear
    inputDir= 'G://ECV_SOIL_MOISTURE_RAW' + "/" + strYear
    print inputDir

    #Loop through all the files within the input directory specified in inputDir
    for root, dirs, filenames in os.walk(inputDir):
        for f in filenames:
            
            #assigns the name of the current file to be converted to geotiff - USER TO MODIFY
            #inFile="C:\\Users\\kpeng\\Desktop\\ecv\\" + strYear + "\\" + f
            inFile="G:\\ECV_SOIL_MOISTURE_RAW\\" + strYear + "\\" + f
            print inFile

            #extracts the clean name of the file
            sm_Layer1 = "ecv_sm_" + f[36:44]

            #cleans the name of the file for export as geotiff
            outFile=outputDir + "ecv_sm_" + f[36:44] + ".tif"
            print outFile
            
            # Process: Make NetCDF Raster Layer
            arcpy.MakeNetCDFRasterLayer_md(inFile, "sm", "lon", "lat", sm_Layer1, "", "", "BY_VALUE")

            # Process: Copy Raster
            arcpy.CopyRaster_management(sm_Layer1, outFile, "", "", "", "NONE", "NONE", "", "NONE", "NONE")

    #increment to loop through files in the next year
    year=year+1



    
